config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
            :path => '',
            :path_name => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
            :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                            :registrations => 'registrations'}

  root "pages#home"

  resources :products do
  	resources :reviews, only: [ :create, :destroy ]
  end

  get "my_products" => "products#my_products"

  resources :charges, only:[:new, :create]

  get "sales" => "products#sales"
  get "purchases" => "products#purchases"
  get "search" => "pages#search"

  resources :contacts, only: [:new, :create]

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true
	validates :body, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :user
	belongs_to :product

end

app/models/product.rb
class Product < ActiveRecord::Base

	has_attached_file :image, styles: { medium: "150x150>", thumb: "100x100>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	validates :name, presence: true
	validates :description, presence: true
 	validates :price, presence: true
 	validates_numericality_of :price

 	self.per_page = 3

 	belongs_to :user
 	has_many :orders
 	has_many :reviews

 	def short_description
 		description.length > 130 ? description[0..130] + "..." : description
 	end

 	def self.search(query)
 		where("name LIKE ? OR description LIKE ?", "%#{query}%", "%#{query}%")
 	end

 	def user_has_order?(user)
 		orders.map(&:user).include?(user)
 	end

 	def is_reviewed?(user)
 		reviews.map(&:user).include?(user)
 	end

 	
end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :user
	belongs_to :product
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :products
  has_many :orders
  has_many :reviews

  def full_name
  	first_name + " " + last_name
  end

  def self.omniauth_facebook(auth)
    user = User.where(email: auth.info.email).first

    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.description = auth.info.description
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => params[:total_price],
	    :description => params[:description],
	    :currency    => 'usd'
	  )

	  product = Product.find(params[:product_id])

	  order = Order.create(
	  	user: current_user,
	  	product: product,
	  	price: params[:price],
	  	quantity: params[:quantity],
	  	total_price: params[:total_price],
	  	stripe_customer_id: customer.id,
	  	stripe_email: customer.email,
	  	currency: charge.currency
	  )

	  redirect_to root_path

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.create(contact_params)

		if @contact.save
			flash[:notice] = "Saved successfully !"

			@name = params[:contact][:name]
			@email = params[:contact][:email]
			@body = params[:contact][:body]

			ContactMailer.contact_email(@name, @email, @body).deliver

			flash[:notice] = "Query sent successfully !"
			redirect_to root_path
		else
			flash[:notice] = "Error, could not be saved !"
			render "new"
		end
	end

	private

	def contact_params
		params.require(:contact).permit(:name, :email, :body)
	end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def facebook
		@user = User.omniauth_facebook(request.env['omniauth.auth'])

		if @user.persisted?
			sign_in_and_redirect @user, :event => 'authentication'
			set_flash_message(:notice, :success, :kind => 'facebook') if is_navigational_format?
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
			redirect_to_new_user_registration_url
		end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def search
  	@products = Product.search(params[:q])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :my_products]
	before_action :find_product, except: [:index, :new, :create, :my_products, :sales, :purchases ]

	def index
		@products = Product.paginate(:page => params[:page]).order("created_at DESC")
	end

	def new
		@product = current_user.products.new
	end

	def create
		@product = current_user.products.create(product_params)

		if @product.save
			flash[:notice] = "Product saved successfully"
			redirect_to products_path
		else
			flash[:notice] = "Error! could not be saved"
			render "new"
		end
	end

	def show
		@review = Review.new
		@reviews = @product.reviews
	end

	def edit
	end

	def update
		if @product.update(product_params)
			flash[:notice] = "Product updated successfully"
			redirect_to products_path
		else
			flash[:notice] = "Error! could not be updated"
			render "edit"
		end
	end

	def destroy
	end

	def my_products
		@products = current_user.products.paginate(:page => params[:page]).order("created_at DESC")
	end

	def sales
		@products = current_user.products
	end

	def purchases
		@orders = current_user.orders
	end

	private

		def product_params
			params.require(:product).permit(:name, :price, :description, :image)
		end

		def find_product
			@product = Product.find(params[:id])
		end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	def new
		super
	end

	def create
		super
	end
	
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def create
		@review = Review.create(review_params)
		@product = @review.product
		if @review.save
			flash[:notice] = "Review saved successfully!"
			redirect_to @product
		end
	end

	def destroy
		@review = Review.find(params[:id])
		@product = @review.product
		@review.delete
		redirect_to @product
	end

	private

	def review_params
		params.require(:review).permit(:user_id, :product_id, :star, :comment)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def avatar_url(user)
		gravatar = Digest::MD5.hexdigest(user.email).downcase
			"https://www.gravatar.com/avatar/#{gravatar}.jpg?s=30"
	end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<h1>Charges#new</h1>
<p>Find me in app/views/charges/new.html.erb</p>

app/views/contacts/new.html.erb
<div class="container">
	<br>
	
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="text-center">Send Your Queries</h1>
			<%= form_for(@contact) do |f| %>
				
				<% if @contact.errors.any? %>
					<ul>
						<% @contact.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				<% end %>

				<div class="form-group">
					<%= f.label :name %>
					<%= f.text_field :name, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :email %>
					<%= f.text_field :email, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :body %>
					<%= f.text_area :body, class: "form-control" %>
				</div>

				<%= f.submit "Send Message", class: "btn btn-info" %>

			<% end %>
		</div>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sixerr3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<%= render "shared/header" %>
	</header>

	<main>
		<% flash.each do |name,msg| %>
			<%= content_tag :div, msg, class: "alert alert-#{name}" %>
		<% end %>

		<%= yield %>
	</main>

	<footer>
		
	</footer>

</body>
</html>

app/views/pages/home.html.erb
<div id="landing-image">
	
</div>
<div class="container">
	<h1>Pages#home</h1>
	<p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/pages/search.html.erb
<div class="container">
	<h1>Search Result</h1>
	<hr>
	<%= render "products/products" %>
</div>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
	
	<% if @product.errors.any? %>
		<ul>
			<% @product.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :image %>
		<%= f.file_field :image, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :price %>
		<%= f.text_field :price, class: "form-control" %>
	</div>
	
	<% if params[:action] == "new" %>
		<%= f.submit "Create Product", class: "btn btn-primary" %>
	<% else %>
		<%= f.submit "Update Product", class: "btn btn-primary" %>
	<% end %>

<% end %>

app/views/products/_products.html.erb
	<% @products.each_slice(3) do |products| %>

		<div class="row">
			<% products.each do |product| %>
				<div class="col-md-4">
					<div class="well">
						<div class="h1"><%= product.name %></div>
						<% if product.image %>
							<%= image_tag(product.image.url(:medium)) %>						
						<% end %>
						<p class="product_description">
							<%= product.short_description %>
							<% if product.description.length > 130 %>
								<%= link_to "view more >>", product_path(product) %>
							<% end %>
						</p>
						<p><%= product.price %></p>
						<hr>
						<%= link_to "Show", product_path(product), class: "btn btn-primary btn-xs" %> 

						<% if current_user && product.user_id == current_user.id %>
							<%= link_to "Edit", edit_product_path(product), class: "btn btn-info btn-xs" %>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>

	<% end %>

app/views/products/edit.html.erb
 <div class="container">
	 <h1>Edit Product</h1>
	 <hr>
	 <%= render "form" %>
 </div>

app/views/products/index.html.erb
<div class="container">
	<h1>All Products</h1>
	<hr>
	<%= will_paginate @products, renderer: BootstrapPagination::Rails %>

	<%= render "products" %>

	<%= link_to "New Product", new_product_path, class: "btn btn-primary" %>	
</div>

app/views/products/my_products.html.erb
<div class="container">

	<h1>My Products</h1>	
	<hr>
	<%= will_paginate @products, renderer: BootstrapPagination::Rails %>
	
	<%= render "products" %>

	<%= link_to "New Product", new_product_path, class: "btn btn-primary" %>	

</div>

app/views/products/new.html.erb
<div class="container">
	<div class="col-md-6 col-md-offset-3">
		<h1>New Product Entry</h1>
		<hr>

		<%= render "form" %>

	</div>
</div>

app/views/products/purchases.html.erb
<div class="container">
	<h1>My Purchases</h1>
	<hr>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Imange</th>
				<th>Name</th>
				<th>Quantity</th>
				<th>Price</th>
				<th>Total Price</th>
				<th>Date Purchased</th>
				<th>Seller</th>
			</tr>
		</thead>
		<tbody>
			<% @orders.each do |order| %>
				<tr>
					<td><%= image_tag(order.product.image.url(:medium)) %></td>
					<td><%= order.product.name %></td>
					<td><%= order.quantity %></td>
					<td><%= order.price %></td>
					<td><%= order.total_price %></td>
					<td><%= order.created_at %></td>
					<td><%= order.product.user.email %></td>
				</tr>
			<% end %>
		</tbody>
	</table>	
</div>

app/views/products/sales.html.erb
<div class="container">
	<h1>My Sales</h1>
	<hr>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Image</th>
				<th>Name</th>
				<th>Quantity</th>
				<th>Price</th>
				<th>Total Price</th>
				<th>Date Sold</th>
				<th>Buyer</th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |product| %>
				<tr>
					<td><%= image_tag(product.image.url(:medium)) %></td>
					<td><%= product.name %></td>

					<% product.orders.each do |order| %>
						<td><%= order.quantity %></td>
						<td><%= order.total_price %></td>
						<td><%= order.user.email %></td>
						<td><%= order.created_at %></td>
						<td><%= order.user.email %></td>
					    </tr>
					    <td></td>
					    <td></td>
					<% end %>

				</tr>
			<% end %>
		</tbody>
	</table>	
</div>

app/views/products/show.html.erb
<div class="container">
	<h1><%= @product.name %></h1>
	<hr>
	<div class="row">
		<div class="col-md-6">
			<%= image_tag(@product.image.url(:medium)) %>
			<h4><%= @product.description %></h4>
		</div>
		<div class="col-md-2">
			
		</div>
		<div class="col-md-4">
			<div class="well">

				<%= form_tag charges_path, id: 'chargeForm' do %>
				  <article>
				    <% if flash[:error].present? %>
				      <div id="error_explanation">
				        <p><%= flash[:error] %></p>
				      </div>
				    <% end %>
				  </article>

				  <script src="https://checkout.stripe.com/checkout.js"></script>
					
					<%= hidden_field_tag 'stripeToken' %>
					<%= hidden_field_tag 'stripeEmail' %>
					<%= hidden_field_tag 'product_id', @product.id %>
					<%= hidden_field_tag 'description', @product.description %>
					<%= hidden_field_tag 'price', @product.price %>
					<%= hidden_field_tag 'total_price', {id: "total_price"} %>


				<button type="button" id="btn-order" class="btn btn-block btn-info btn-order">
					Order Now-(<%= @product.price %>)
				</button>

				<script type="text/javascript">
					var handler = StripeCheckout.configure({
						key: '<%= Rails.configuration.stripe[:publishable_key] %>',
						token: function(token, arg) {
							document.getElementById("stripeToken").value = token.id,
							document.getElementById("stripeEmail").value = token.email,
							document.getElementById("chargeForm").submit();
						}
					});

					document.getElementById("btn-order").addEventListener('click', function(e){
						var quantity = $('#quantity').val();
						var total_price = (quantity * "<%= @product.price %>") + "00";
						$('#total_price').val(total_price);
						handler.open({
							name: "Sixerr3",
							description: "<%= @product.description %>",
							amount: total_price
						});
						e.preventDefault();
					});
				</script>

				<hr>
				Select Quantity: 
				<%= select_tag(:quantity, options_for_select([
					["1 (£#{@product.price * 1})", 1],	
					["2 (£#{@product.price * 2})", 2],	
					["3 (£#{@product.price * 3})", 3],	
					["4 (£#{@product.price * 4})", 4],	
					["5 (£#{@product.price * 5})", 5]	
					])) %>
				<% end %>
			</div>
		</div>
	</div>
	
	<div class="row">
		
		<h2>Reviews</h2>

		<% @reviews.each do |review| %>
			<div class="row">
				<div class="col-md-1">
					<%= image_tag avatar_url(review.user), class: "img-circle" %>
				</div>

				<div class="col-md-2">
					<div id="review_star_<%= review.star %>"></div>
				</div>

				<div class="col-md-4">
					<%= review.comment %>
				</div>

				<div class="col-md-1">
					<%= link_to "Delete", product_review_path(@product, review), method: :delete, data: {confirm: "Sure to delete?"}, class: "btn btn-xs btn-danger" %>
				</div>
			</div>

			<script>
				$('#review_star_<%= review.star %>').raty({
					path: '/assets',
					score: <%= review.star %>,
					readOnly: true
				});
			</script>

		<% end %>

		<%= render "reviews/form" if @product.user_has_order?(current_user) && !@product.is_reviewed?(current_user) %>

	</div>

</div>

<script>
	$(document).ready(function(){
		$("select").bind("change", function(){
			$('.btn-order').html("Order Now - " + $("select option:selected").html());
		});

		$('#star_input').raty({
			path: '/assets',
			score: 1,
			scoreName: 'review[star]'
		});
	})
</script>

app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |f| %>
	
	<%= f.hidden_field :user_id, value: current_user.id %>
	<%= f.hidden_field :product_id, value: @product.id %>

	<div class="form-group">
		<div id="star_input"></div>
		<%= f.text_area :comment, class: "form-control" %>
	</div>
	<%= f.submit "Submit Review", class: "btn btn-default" %>

<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <li><%= link_to "SIXERR3", root_path, class: "navbar-brand" %></li>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Products", products_path %></li>
              <li><%= link_to "My Products", my_products_path %></li>
            </ul>
          </li>

          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Orders <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Sales", sales_path %></li>
                <li><%= link_to "Purchases", purchases_path %></li>
              </ul>
            </li>
          
          <% end %>
      </ul>

      <%= form_tag search_path, method: :get, class: "navbar-form navbar-left" do %>
        <div class="form-group">
          <%= text_field_tag :q, nil, placeholder: "Search Product", class: "form-control" %>
        </div>
        <%= submit_tag "Submit", class: "btn btn-default" %>
      <% end %>

      <div class="nav navbar-nav">
        <%= link_to "Contact Us", new_contact_path, class: "btn btn-primary navbar-btn" %>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "img-circle" %>
              <%= current_user.full_name %>
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, data: { confirm: "Sure to Log Out?" } %></li>
            </ul>
          </li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>